# Generated by Django 3.0.4 on 2020-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brandimage',
            fields=[
                ('bisno', models.AutoField(primary_key=True, serialize=False)),
                ('brand_imgurl', models.URLField(verbose_name='BRAND IMAGE URL')),
                ('brand_logourl', models.URLField(verbose_name='BRAND LOGO URL')),
                ('brand_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('bsno', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('tranding_product', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('product_desc', models.TextField()),
                ('product_brand', models.CharField(max_length=255)),
                ('product_imgurl', models.URLField(verbose_name='PRODUCT IMAGE URL')),
                ('product_price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('WEIGHTLOSS', 'WEIGHTLOSS'), ('DAILYVITALS', 'DAILYVITALS'), ('MASSGAINERS', 'MASSGAINERS')], max_length=20)),
            ],
        ),
    ]
