# Generated by Django 3.0.4 on 2020-06-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='product_imgurl1',
            field=models.URLField(null=True, verbose_name='PRODUCT IMAGE URL1'),
        ),
        migrations.AddField(
            model_name='brands',
            name='product_imgurl2',
            field=models.URLField(null=True, verbose_name='PRODUCT IMAGE URL2'),
        ),
        migrations.AddField(
            model_name='brands',
            name='product_imgurl3',
            field=models.URLField(null=True, verbose_name='PRODUCT IMAGE URL3'),
        ),
        migrations.AddField(
            model_name='brands',
            name='product_weight',
            field=models.IntegerField(default=0),
        ),
    ]
