# Generated by Django 3.0.4 on 2020-06-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_auto_20200608_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='product_weight',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
