# Generated by Django 3.0.4 on 2020-06-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0004_auto_20200608_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandimage',
            name='brand_name',
            field=models.CharField(choices=[('apple', 'appleapple'), ('samsung', 'samsung'), ('lg', 'lg'), ('mi', 'mi'), ('nokia', 'nokia'), ('vivo', 'vivo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brands',
            name='product_brand',
            field=models.CharField(choices=[('apple', 'appleapple'), ('samsung', 'samsung'), ('lg', 'lg'), ('mi', 'mi'), ('nokia', 'nokia'), ('vivo', 'vivo')], max_length=255),
        ),
    ]
