# Generated by Django 3.0.4 on 2020-06-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0005_auto_20200608_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='product_percent_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brandimage',
            name='brand_name',
            field=models.CharField(choices=[('apple', 'apple'), ('samsung', 'samsung'), ('lg', 'lg'), ('mi', 'mi'), ('nokia', 'nokia'), ('vivo', 'vivo'), ('jio', 'jio'), ('opo', 'opo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brands',
            name='product_brand',
            field=models.CharField(choices=[('apple', 'apple'), ('samsung', 'samsung'), ('lg', 'lg'), ('mi', 'mi'), ('nokia', 'nokia'), ('vivo', 'vivo'), ('jio', 'jio'), ('opo', 'opo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brands',
            name='product_category',
            field=models.CharField(choices=[('weight loss', 'weight loss'), ('daily vitals', 'daily vitals'), ('mass gainers', 'mass gainers')], max_length=20),
        ),
    ]
