# Generated by Django 3.0.4 on 2020-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0006_auto_20200608_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('csno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
