# Generated by Django 3.0.4 on 2020-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0009_auto_20200611_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='product_imgurl1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PRODUCT IMAGE URL1'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='product_imgurl2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PRODUCT IMAGE URL2'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='product_imgurl3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PRODUCT IMAGE URL3'),
        ),
    ]
