# Generated by Django 3.0.4 on 2020-06-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0010_auto_20200611_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='product_imgurl',
            field=models.CharField(max_length=255, verbose_name='PRODUCT IMAGE URL'),
        ),
    ]
