# Generated by Django 3.0.4 on 2020-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0011_auto_20200611_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsJson', models.TextField(verbose_name='Orderd Products')),
                ('amount', models.IntegerField(verbose_name='Total Price Of All Products')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Costumer')),
                ('address1', models.CharField(max_length=255, verbose_name='Costomer Addresh Line 1')),
                ('address2', models.CharField(max_length=255, verbose_name='Costomer Addresh Line 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Costumer Email')),
                ('city', models.CharField(max_length=25, verbose_name='Costomer City')),
                ('state', models.CharField(max_length=30, verbose_name='Costomer State')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code Of Costomer')),
                ('phone', models.IntegerField(verbose_name='Costomer Phone Number')),
            ],
        ),
    ]
